#!/bin/bash
emulate_click() {
    declare x=$1 y=$2
    if xdotool getactivewindow getwindowname | grep -q 'Foxit Reader'; then
        xdotool mousemove --sync $x $y click --clearmodifiers 1 mousemove --sync restore
    else
        exit 1
    fi
}

main() {
    if (($# == 1)); then
        declare cmd=$1
    else
        exit 1
    fi

    case $cmd in
        highlight )
            declare pos=(22 148)
            ;;
        underline )
            declare pos=(111 148)
            ;;
        inline-text )
            declare pos=(301 148)
            ;;
    esac

    emulate_click "${pos[@]}"
}

main "$@"
