#!/bin/bash
pkill -f i3activity-detect
# inactivity timeout 5min, with 10s delay
declare timeout=300
declare delay=10
xset s $timeout $delay
i3activity-detect &
exec xss-lock -n "notify-send --urgency=low 'Screen Lock' 'Screen will be locked in "$delay" seconds.'" \
        -- i3exit lock --nofork
