#!/bin/bash
pkill -f i3activity-detect
i3activity-detect &
exec xautolock -time 5 -locker "~/bin/i3exit lock" \
        -notify 10 \
        -notifier "notify-send --urgency=low 'Screen Lock' 'Screen will be locked in 10 seconds.'" \
        -detectsleep
