#!/bin/bash
safely_quit_vim() (
    echo "Saving vim sessions..." 1>&2
    # fork subshell to restrict effects of environ change
    declare -x DISPLAY=:0
    vim --serverlist | xargs --max-args=1 \
                             --no-run-if-empty -I'{}' \
                             vim --servername '{}' --remote-send '<Esc><Esc>:wqa<CR>'
    return $?
)


sync_data() {
    echo "Syncing buffers to disks..." 1>&2
    sync
}


suspend_to_disk() {
    echo "Start suspend..." 1>&2
    sudo systemctl hibernate
}


main() {
    safely_quit_vim && sync_data && suspend_to_disk
}

main
