bashrc: ~/.bashrc
cvimrc: ~/.cvimrc
environment: /etc/environment
fonts: ~/.fonts
gdbinit: ~/.gdbinit
ghci: ~/.ghci
git-prompt.sh: ~/.git-prompt.sh
gitconfig: ~/.gitconfig
gitignore: ~/.gitignore
gtk.css: ~/.config/gtk-3.0/gtk.css
inputrc: ~/.inputrc
vim: ~/.vim
pip.conf: ~/.config/pip/pip.conf
smb.conf: /etc/samba/smb.conf
sysctl.conf: /etc/sysctl.conf
updatedb.conf: /etc/updatedb.conf
pre-commit: /usr/share/git-core/templates/hooks/pre-commit
texmf: ~/texmf
#ipsec.conf: /etc/strongswan/ipsec.conf
